// fontawesome.js
import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faTimes, 
  faEdit, 
  faEnvelope, 
  faTimesCircle, 
  faCalendarAlt, 
  faFilePdf, 
  faExternalLinkAlt, 
  faCheck,
  faFileAlt,
  faPaperPlane,
  faSpinner,
  faPlus,
  faUser,
  faIdCard,
  faPhone,
  faMapMarkerAlt,
  faGraduationCap,
  faBriefcase,
  faHeart,
  faChevronDown,
  faChevronUp,
  faEllipsisV,
  faTrash,
  faDownload,
  faCog,
  faSignOutAlt,
  faBell
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library so you can use them without importing individually
library.add(
  faTimes, 
  faEdit, 
  faEnvelope, 
  faTimesCircle, 
  faCalendarAlt, 
  faFilePdf, 
  faExternalLinkAlt, 
  faCheck,
  faFileAlt,
  faPaperPlane,
  faSpinner,
  faPlus,
  faUser,
  faIdCard,
  faPhone,
  faMapMarkerAlt,
  faGraduationCap,
  faBriefcase,
  faHeart,
  faChevronDown,
  faChevronUp,
  faEllipsisV,
  faTrash,
  faDownload,
  faCog,
  faSignOutAlt,
  faBell
);
